### PR TITLE
feat: fetch latest credo-language-server version

### PR DESCRIPTION
**Pull request by mhanberg**

### CODE REVIEW

**Comment by mhanberg** [comment]
Current dependencies on/for this PR:
* main
  * **PR #11** <a href="https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/11" target="_blank">Graphite</a> 
    * **PR #12** <a href="https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/12" target="_blank">Graphite</a>  👈
      * **PR #13** <a href="https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/13" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/12?utm_source=stack-comment).

**Comment by mhanberg** [comment]
Current dependencies on/for this PR:
* main
  * **PR #11** <a href="https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/11" target="_blank">Graphite</a> 
    * **PR #12** <a href="https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/12" target="_blank">Graphite</a>  👈
      * **PR #13** <a href="https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/13" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/12?utm_source=stack-comment).

**Comment by mhanberg** [comment]
@CoderDennis Do you have any idea what these errors are about? (I don't really know much about node or typescript)

**Comment by CoderDennis** [comment]
@mhanberg I'm not sure yet why the errors are happening, but they all seem to be from the new `node-fetch` dependency and its dependencies. The fetch API was added to Node 18, so maybe your question about which node version vscode uses is more relevant than I thought. I tried a quick google search, but haven't found the answer yet.

**Comment by mhanberg** [comment]
I can replicate the failures on node 16

**Comment by mhanberg** [comment]
[Graphite](https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/12) rebased this pull request as part of a merge.

**Comment by mhanberg** [comment]
@mhanberg merged this pull request with [Graphite](https://app.graphite.dev/github/pr/elixir-tools/elixir-tools.vscode/12).

**Pull request merged**
